packages:
  - apps/*
  - libs/*

ignoredBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - better-sqlite3
  - prisma
  - sharp

onlyBuiltDependencies:
  - "@sentry/cli"
  - "@swc/core"
  - bcrypt
  - core-js
  - esbuild
  - msw
  - nx
  - unrs-resolver

peerDependencyRules:
  allowAny:
    - "@better-auth/*"
    - "@better-call/*"
    - better-auth
    - better-call
    - react

publicHoistPattern:
  - "*import-in-the-middle*"
  - "*require-in-the-middle*"
